### ISSUE TITLE
Accept and log push button response to telephone reminder

### ISSUE THREAD

**Issue by DeckOfPandas** [takeyourmeds/takeyourmeds-web#46] opened 2015-09-17 17:37 UTC

**Comment by lamby** [comment] 2015-09-19 16:13
I wonder if this is just "another" state for #47 - eg. some kind of `NO_ANSWER` vs `ANSWERED` state?

**Comment by lamby** [comment] 2015-11-04 19:47
dupe of #48

**Closed as completed** 2015-11-04 19:48 UTC
Labels: enhancement
