### ISSUE TITLE
Log phone calls made/suceeded/failed

### ISSUE THREAD

**Issue by DeckOfPandas** [takeyourmeds/takeyourmeds-web#47] opened 2015-09-17 17:38 UTC
Twilio API spits this out fairly nicely

**Comment by lamby** [comment] 2015-09-19 16:12
One dev question would be whether we store these locally or pull them from Twilio when we need to display them. Gut says the former..

**Comment by lamby** [comment] 2015-11-04 19:47
dupe of #48

**Closed as completed by lamby** 2015-11-04 19:47 UTC
Labels: enhancement
